version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=${APP_PORT}
      - SERVER_SERVLET_CONTEXT_PATH=${APP_CONTEXT_PATH}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:${KEYCLOAK_PORT}/auth/realms/${KEYCLOAK_REALM}
      - CIELO_API_URL=${CIELO_API_URL}
      - CIELO_MERCHANT_ID=${CIELO_MERCHANT_ID}
      - CIELO_MERCHANT_KEY=${CIELO_MERCHANT_KEY}
      - CIELO_ENVIRONMENT=${CIELO_ENVIRONMENT}
      - PAYPAL_API_URL=${PAYPAL_API_URL}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - STRIPE_API_URL=${STRIPE_API_URL}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    depends_on:
      - db
      - rabbitmq
      - keycloak
    networks:
      - gateway-network

  db:
    image: postgres:16-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gateway-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - gateway-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_PROXY=edge
    command: start-dev
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - gateway-network

volumes:
  postgres-data:

networks:
  gateway-network:
    driver: bridge
